USE_CAMERA_STUB := true

# inherit from the proprietary version
-include vendor/zte/P692N30/BoardConfigVendor.mk

TARGET_ARCH := arm
TARGET_NO_BOOTLOADER := true
TARGET_BOARD_PLATFORM := mt6592
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
ARCH_ARM_HAVE_TLS_REGISTER := true

TARGET_BOOTLOADER_BOARD_NAME := P692N30

BOARD_KERNEL_CMDLINE := 
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x105c0000
BOARD_FLASH_BLOCK_SIZE := 131072

TARGET_PREBUILT_KERNEL := device/zte/P692N30/kernel

BOARD_HAS_NO_SELECT_BUTTON := true

#Make Recovery
TOOLS_DIR := device/zte/P692N30/tools
RECOVERY_ROOT_DIR := out/target/product/P692N30/recovery/root
BOARD_CUSTOM_BOOTIMG_MK := device/zte/P692N30/mkbootimg.mk

#Common Recovery
RECOVERY_FSTAB_VERSION := 2

#Recovery
TARGET_RECOVERY_PIXEL_FORMAT := "RGBA_8888"
TARGET_RECOVERY_FSTAB := device/zte/P692N30/recovery.fstab

#TWRP Recovery
TW_ALWAYS_RMRF := true
TW_FLASH_FROM_STORAGE:= true
DEVICE_RESOLUTION := 720x1280
TW_NO_REBOOT_BOOTLOADER := true
